version: '3.9'
services:
  aimym-dashboard:
    build: .  # Builds from Dockerfile
    container_name: moneysq-landing
    ports:
      - "5173:5173"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lb-net

networks:
  lb-net:
    driver: bridge